### ISSUE TITLE
sqlite problems like Unable to create empty record

### ISSUE THREAD

**Issue by lyudmila-petrova** [oslabs-beta/infernode#232]
```
Error: Unable to create empty record
    at callback (/home/.../node_modules/infernode/dist/controllers/db.controller.js:65:29)
    at replacement (/home/.../node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/home/.../node_modules/sqlite3/lib/sqlite3.js:15:21)
Error: Unable to retrieve row information
    at /home/.../node_modules/infernode/dist/controllers/db.controller.js:37:29
    at replacement (/home/.../node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/home/.../node_modules/sqlite3/lib/sqlite3.js:15:21)

```

node 18

due to sqlite errors ui is useless

**Comment by 8000meters** [comment]
Please provide steps to re-create this error.
